
services:
  proxy:
    image: traefik:v3.1
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.api.address=:80"
      - "--entryPoints.web-secure.address=:443" # Declares the web-secure entrypoint in Traefik
      - "--certificatesresolvers.myleresolver.acme.email=josephjomon401@gmail.com"
      - "--certificatesresolvers.myleresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myleresolver.acme.tlschallenge=true"

    ports:
      - "80:80"
      - "443:443" #Docker sends requests on port 443 to Traefik on port 443
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  odoo18:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo  # 'the local etc should contain odoo.conf(fully commented out is also ok) and the requirements.txt for installing extra modules'
    labels:
      #----------------------------------------------- routers for: odoo --------------------------------------------------
      - "traefik.http.routers.router_rule_01.entryPoints=web-secure" # gave name to the router(router_rule_01) and specified its entrypoint(api)
      - "traefik.http.routers.router_rule_01.rule=Host(`website.kundalin.com`)" # specified the routing rule of the router(router_rule_01)
      - "traefik.http.routers.router_rule_01.service=odoo" # Explicit definition of a router(router_rule_01) with one service(service_01)
      - "traefik.http.routers.router_rule_01.tls=true"
      - "traefik.http.routers.router_rule_01.tls.certresolver=myleresolver"
      - "traefik.http.routers.router_rule_01.middlewares=gzip,sslheader,limit" # Definition of a Service(service_01) running on the container [https://doc.traefik.io/traefik/routing/providers/docker/#service-definition]
      #----------------------------- routes for: odoo/web/database || odoo/website/info  -----------------------------
      # https 
      - traefik.http.routers.router_rule_02.rule=Host(`website.kundalin.com`) && (PathPrefix(`/web/database`) || PathPrefix(`/admin/info`))
      - traefik.http.routers.router_rule_02.entrypoints=web-secure
      - traefik.http.routers.router_rule_02.service=odoo
      - traefik.http.routers.router_rule_02.tls.certresolver=myleresolver
      - traefik.http.routers.router_rule_02.middlewares=gzip,sslheader,limit
      #---------------------------------------- routes for: odoo/longpolling ------------------------------------------------
      # https 
      - traefik.http.routers.router_rule_03.rule=Host(`website.kundalin.com`) && (PathPrefix(`/longpolling`))
      - traefik.http.routers.router_rule_03.entrypoints=web-secure
      - traefik.http.routers.router_rule_03.service=odoo-im
      - traefik.http.routers.router_rule_03.tls.certresolver=myleresolver
      - traefik.http.routers.router_rule_03.middlewares=gzip,sslheader,limit


      #====================================================== services ===========================================================
      - traefik.http.services.odoo.loadbalancer.server.port=8069
      - traefik.http.services.odoo-im.loadbalancer.server.port=8072
      #===================================================== middlewares =========================================================
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=20971520
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=20971520

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:


